### ISSUE TITLE
Error handling response: TypeError: Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by DavidTeju** [anuraglodhi13/LeetCodeForcer#4]
https://github.com/anuraglodhi13/LeetCodeForcer/blob/402e6042c78733bc70d9c33d9d0b8000547f7407/leetcode-forcer/background.js#L59

I'm having issues where this line is throwing the following error quite randomly:
Error handling response: TypeError: Cannot read properties of undefined (reading 'url')
    at chrome-extension://bfhandefodflloblgbmckmildnmangcb/background.js:59:45

My suspicion is that the extension might be running while the person is inputting a new URL or something of that sort. Should be a simple try/catch and recall the initial function in the catch.

**Comment by golldyydev** [comment]
A simple try-catch block should suffice. In the catch block, we can return the function, since chrome.tabs.onUpdated will be triggered whenever the URL changes.

**Comment by golldyydev** [comment]
Thanks for brings out this issue. I have fixed this issue. Closing it for now, you can check if issue still persist or not.
